### PR TITLE
Update Yume 2kki locations

### PR DESCRIPTION
**Pull request by Claustra**

### CODE REVIEW

**Comment by Flashfyre** [comment]
I appreciate the work done here, but what is the primary purpose of adding (presumably) every location here? Locations not specified (most) are pulled from Explorer through its API, which removes the need to constantly update this file and means less work for us. There are some benefits to having them all in the file (no query needed for locations, localization to multiple languages is a huge plus), but it needs that it needs to be regularly updated and Yume 2kki updates very frequently.

**Comment by Claustra** [comment]
The purpose of this is to fix all Japanese location names. I didn't add every location: I excluded some entries that are correct names which retrieved from API.
Currently, Japanese location name are based on English location names. Thus, most of Japanese location has wrong names. So I just wanted to fix all Japanese names.

Or am I wrong?

**Comment by Flashfyre** [comment]
If the goal is to fix the Japanese location names, the changes should be made on the wiki, which they're pulled from. There is a JapaneseName field in the template of each location page. This will fix incorrect names on the Explorer too, which will be broken by these changes due to differing names.

https://yume.wiki/2kki/Yume_2kki_Wiki

**Comment by Flashfyre** [comment]
It seems you handled URL titles as well, so perhaps it does work with Explorer as-is, though the names on Explorer in Japanese will still be inaccurate. I do see the benefit of displaying sub-areas, so perhaps we should add these changes on top of changing the wiki, which does not have to be done by you.

**Comment by Claustra** [comment]
What I meant of wrong Japanese names are all English sub-area so I cannot fix them by editing yume.wiki.

**Comment by Flashfyre** [comment]
That makes sense, I understand now. Thank you.

**Review by Flashfyre — APPROVED** [review]

**Pull request merged**
